lttng-modules: Upgrade version from 2.9.0 to 2.9.3
Upgrade to a new version of lttng-modules, used in yocto master
branch to include some fixes for preempt-rt kernel version.

Details of the failure in:
A0177 - Yocto Linux Builds Fail with the Latest 4.9 and Preempt-RT

./probes/lttng-tracepoint-event-impl.h:142:6: error: conflicting
                              typpes for 'trace_sched_pi_setprio'

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>