linux-yocto: Update branch names for 3.10 and 3.14
Set standard/axxia-dev/base branch for builds that use kernel
from Github repo.
* standard/axxia-dev/base is development area
for axxia team having latest changes before pushing to Yocto
and is used in private builds.
* standard/axxia/base should match exactly what's in Yocto; only
happens after pushed to customer; used in public builds

So, axxia team will use private builds to have development branch
and customers will build from public branch to have latest commits
before are pushed to Yocto and will use yocto builds to have the
clean kernel repo.

Also, set AUTOREV for public builds also because patches are merged
private to public only after are tested. So it's easier to maintain.

Also set AUTOREV for 3.10 META branch to avoid validation test failure
on do_validate_branches task
If SRCREV_meta is not set, it will have the value from upstream
which is not found in our kernel tree from github.

fatal: git cat-file <SHA declared upstream - in poky>: bad file
ERROR:  <SHA declared upstream - in poky> is not a valid commit ID
ERROR: The kernel source tree may be out of sync

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>