linux: 4.19: Temporary use clean branches for 4.19.30
*-clean branches was rebased on 4.19.30 and include commit
0ac569bf6a79 ("ARM: 8834/1: Fix: kprobes: optimized kprobes
illegal instruction") which fix teh following lttng-modules
version 2.10.9 error:

lttng-modules-2.10.9/probes/../blacklist/kprobes.h:19:4:
     error: #error "Your kernel is known to have buggy optimized
            kprobes implementation

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>