simicsfs: Update to 1.22 version for kernel 4.12 support
Added support for Linux kernel version 4.12.
- generic_readlink replaced by vfs_readlink.
- Type casting to long from int for hostfs_getattr:

  | .../simicsfs-mod/1.20-r0/hostfs_inode.c:750:13: error:
  |     initialization from incompatible pointer type
  |     [-Werror=incompatible-pointer-types]
  |   .getattr = hostfs_getattr,

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>