linux-yocto: 4.8: Fix axxiaarm[64] builds
4.8 support for axxiax86-64 machine make builds for other
machines to fail:

Error executing a python function in <code>:
Exception: bb.fetch2.MalformedUrl: The URL:
'${KREPO_KERNEL};name=machine;branch=standard/base'
is invalid and cannot be interprete

Fix this by making to not depend one another.

B0087: Support for Linux 4.8 in meta-axxia (morty branch)
       Breaks Other Builds

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>