bluez: Force to use only version bluez5 instead of bluez4
By default, both versions of bluez package were compiled and this
cause some warnings and errors because both pachages are trying to
install same files in same locations:

WARNING: The recipe bluez4/bluez5 is trying to install files into a
shared area when those files already exist.
ERROR: Recipe bluez4 is trying to change PR from 'r5' to 'r0'. This
will cause do_package_write_* failures since the incorrect data will
be used and they will be unable to find the right workdir.
ERROR: Function failed: read_subpackage_metadata

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>