gcc: Fix fortran compiling error when building SDK
With fortran support added, building the SDK will fail due to missing
libquadmath library.
fatal error: quadmath_weak.h: No such file or directory

Backporting and adapting upstream OE-core commit from 1.6 daisy branch:

(From OE-Core rev: cae2315266b704614fe1d7bdeef004ef67a01e8d)

gcc 4.8 fortran presents some challenges:
  * libquadmath headers need to be in the libexec include dir. It turns out
    to be easiest just to manually do this in gcc-cross.
  * libgfortran configure needs libquadmath to be compiled. This means
    a separate recipe is needed (the alternative is gross hacks)

Since libgfortran isn't a gcc-runtime component anymore and have a separate
receipe, added it to DEPENDS for lsi-image-large and removed from RUNTIMETARGET
variable.

Also, when configuring libgfortran, syslinks are created for the gcc
libraries but have wrong target path and the symlinks are not valid.
Corrected libgcc symlinks.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>