machine/axxia: Skip kernel bbappend from meta-virtualization
For axxia kernel (from Github)a defconfig is used, so skip bbappend
from meta-virtualization which add kernel fragments which are not found:

WARNING: addon feature "features/kvm/qemu-kvm-enable" was not found
ERROR: required features were not found. aborting

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>