gcc-runtime: Clean shared data for libgfortran
Completing commit
gcc: Fix fortran compiling error when building SDK

- Since libgfortran has his separate receipe, we need to clean the shared
  data for libgfortran installed by gcc-runtime receipe.
  Otherwise, this warning will occur:

  WARNING: The recipe libgfortran is trying to install files into a shared
  area when those files already exist.

  This warning didn't affect the final binaries, but it says that cache dir
  declared in SSTATE_DIR var will be left in an inconsistent condition.
  This will lead to this error when the same sstate-cache directory is
  used by another build(s):

ERROR: libgfortran not found in the base feeds

- Also renamed the pachages for libgfortran receipe

- Uncomment the lines from gcc-cross bbappend to be sure that
  libquadmath headers will be available in the gcc libexec dir.
  This is needed by libgfortran as libquadmath is his dependency.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>